apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-stack.fullname" . }}-backend
  labels: {{- include "otel-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector: {{- include "otel-stack.selectorLabelsBackend" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http