{{- if and .Values.backend.secretRefs.ch.enabled (not .Values.backend.secretRefs.ch.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otel-stack.fullname" . }}-ch
  labels: {{- include "otel-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  CH_USER: {{ default "default" .Values.backend.env.CH_USER | quote }}
  CH_PASS: {{ default "" .Values.backend.env.CH_PASS | quote }}
{{- end -}}