apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-stack.fullname" . }}-ui
  labels: {{- include "otel-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels: {{- include "otel-stack.selectorLabelsUI" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-stack.selectorLabelsUI" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}{{ toYaml . | nindent 8 }}{{- end }}
      annotations:
        {{- with .Values.ui.podAnnotations }}{{ toYaml . | nindent 8 }}{{- end }}
    spec:
      serviceAccountName: {{ default (include "otel-stack.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports: [{ name: http, containerPort: 80 }]
          env:
            {{- range $k, $v := .Values.ui.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- range .Values.ui.extraEnv }}
            - name: {{ .name }}{{ if .value }}{{ printf "\n              value: %q" .value }}{{ end }}
            {{- end }}
          envFrom:
            {{- toYaml .Values.ui.extraEnvFrom | nindent 12 }}
          livenessProbe: {{- toYaml .Values.ui.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.ui.readinessProbe | nindent 12 }}
          resources: {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.ui.extraVolumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.ui.extraVolumes | nindent 8 }}